package br.com.pet2love.model;

public enum Raca {
	AFGHAN("AFGHAN", "AFGHAN HOUND"),
	AIREDALE_TERRIER("AIREDALE", "AIREDALE TERRIER"),
	AKITA("AKITA", "AKITA"),
	ANGORA_GATO("ANGORA", "ANGORA"),
	AMERERICAN_STAFFORDSHIRE("AMERERICAN STAFFORDSHIRE", "AMERERICAN STAFFORDSHIRE TERRIER"),
	AUSTRALIAN("AUSTRALIAN CATTLE DOG", "AUSTRALIAN CATTLE DOG(BOIADEIRO AUSTRALIANO"),
	BASENJI("BASENJI", "BASENJI"),
	BASSET("BASSET", "BASSET HOUND"),
	BEAGLE("BEAGLE", "BEAGLE"),
	BERNESE("BERNESE", "BERNESE MOUNTAIN DOG"),
	BICHON("BICHON", "BICHON FRISE"),
	BLOODHOUND("BLOODHOUND", "BLOODHOUND"),
	BORDER("BORDER","BORDER COLLIE"),
	BORZOI("BORZOI", "BORZOI"),
	BOSTON("BOSTON",  "BOSTON TERRIER"),
	BOXER("BOXER", "BOXER"),
	BULDOGUE_FRANCÊS("BULDOGUE FRANCÊS", "BULDOGUE FRANCÊS"),
	BULDOGUE_INGLÊS("BULDOGUE INGLÊS", "BULDOGUE INGLÊS (BULLDOG)"),
	BULL_TERRIER("BULL", "BULL TERRIER"),
	BULLMASTIFF("BULLMASTIFF", "BULLMASTIFF"),
	BURMESE("BURMESE", "BURMESE"),
	BRITISH_GATO("BRITISH SHORTHAIR", "BRITISH SHORTHAIR"),
	CANE("CANE", "CANE CORSO"),
	CAO_DE_CRISTA("CAODECRISTA", "CÃO DE CRISTA CHINÊS"),
	CAVALIER("CAVALIER", "CAVALIER KING CHARLES SPANIEL"),
	CHIHUAHUA("CHIHUAHUA", "CHIHUAHUA"),
	CHOW("CHOW",  "CHOW CHOW"),
	COCKER_SPANIEL_AMERICANO("COCKER SPANIEL AMERICANO", "COCKER SPANIEL AMERICANO"),
	COCKERS_SPANIEL_INGLÊS("COCKER SPANIEL INGLÊS", "COCKER SPANIEL INGLÊS"),
	COLLIE("COLLIE", "COLLIE"),
	DACHSHUND("DACHSHUND", "DACHSHUND (TECKEL)"),
	DALMATA("DALMATA", "DÁLMATA"),
	DOBERMAN("DOBERMAN", "DOBERMAN"),
	DOGO("DOGO", "DOGO ARGENTINO"),
	DOGUEALEMAO("DOGUE-ALEMAO", "DOGUE-ALEMAO"),
	DOGUEBORDEAUX("DOGUEBORDEAUX", "DOGUE DE BORDEAUX"),
	FILA("FILA", "FILA BRASILEIRO"),
	FOX("FOX", "FOX PAULISTINHA"),
	GOLDEN("GOLDEN", "GOLDEN RETRIEVER"),
	GREYHOUND("GREYHOUND", "GREYHOUND"),
	GRIFFON("GRIFFON", "GRIFFON DE BRUXELAS"),
	HUSKY("HUSKY", "HUSKY SIBERIANO"),
	HIMALAIA_GATO("HIMALAIA", "HIMALAIA"),
	JACK("JACK", "JACK RUSSELL TERRIER"),
	KUVASZ("KUVASZ", "KUVASZ"),
	LABRADOR("LABRADOR", "LABRADOR"),
	LEAODARODESIA("LEÃODARODESIA", "LEÃO DA RODÉSIA – RHODESIAN RIDGEBACK"),
	LHASA("LHASA", "LHASA APSO"),
	LULU("LULU", "LULU DA POMERÂNIA SPITZ ALEMÃO"),
	MALAMUTE("MALAMUTE", "MALAMUTE DO ALASCA"),
	MALTES("MALTES", "MALTÊS"),
	MASTIFF("MASTIFF", "MASTIFF"),
	MAINECONN_GATO("MAINE CONN", "MAINE CONN"),
	SHEEPDOG("SHEEPDOG", "SHEEPDOG"),
	OLD("OLD", "OLD ENGLISH SHEEPDOG"),
	PAPILLON("PAPILLON", "PAPILLON"),
	PASTOR_ALEMAO("PASTOR ALEMAO", "PASTOR ALEMÃO (CAPA PRETA)"),
	PASTOR_AUSTRALIANO("PASTOR AUSTRALIANO", "PASTOR AUSTRALIANO"),
	PASTOR_BELGA("PASTOR BELGA", "PASTOR BELGA"),
	PASTOR_BRANCO("PASTOR BRANCO", "PASTOR BRANCO SUÍÇO (PASTOR CANADENSE)"),
	PASTOR_DESHETLAND("PASTOR DESHETLAND", "PASTOR DE SHETLAND"),
	PASTOR_MAREMANO("PASTOR MAREMANO", "PASTOR MAREMANO ABRUZÊS"),
	PEQUINES("PEQUINES", "PEQUINÊS"),
	PINSCHER("PINSCHER", "PINSCHER"),
	PITBULL("PITBULL", "PIT BULL (AMERICAN PIT BULL TERRIER)"),
	POINTER(",POINTER", "POINTER INGLÊS"),
	POODLE("POODLE", "POODLE"),
	PUG("PUG", "PUG"),
	PERSA_GATO("PERSA", "PERSA"),
	ROTTWEILER("ROTTWEILER", "ROTTWEILER"),
	RAGDOLL_GATO("RAGDOLL", "RAGDOLL"),
	SAMOIEDA("SAMOIEDA", "SAMOIEDA"),
	SAO_BERNARDO("SAOBERNARDO", "SÃO BERNARDO"),
	SCHNAUZER("SCHNAUZER", "SCHNAUZER MINIATURA"),
	SETTER("SETTER", "SETTER IRLANDÊS"),
	SHAR("SHAR", "SHAR PEI"),
	SHIBA("SHIBA", "SHIBA INU"),
	SHIH("SHIH" ,"SHIH TZU"),
	SIAMES_GATO("SIAMES", "SIAMÊS"),
	SIBERIANO_GATO("SIBERIANO", "SIBERIANO"),
	SPHYNX_GATO("SPHYNX", "SPHYNX"),
	SPITZ("SPITZ", "SPITZ JAPONÊS"),
	STAFFORDSHIRE("STAFFORDSHIRE", "STAFFORDSHIRE BULL TERRIER"),
	TERRA("TERRA", "TERRA-NOVA"),
	WEIMARANER("WEIMARANER", "WEIMARANER"),
	WELSHCORGI_CARDIGAN("WELSH CORGI CARDIGAN", "WELSH CORGI CARDIGAN"), 
	WELSHCORGI_PEMBROKE("WELSHCORGIPEMBROKE", "WELSH CORGI PEMBROKE"),
	WEST("WEST", "WEST HIGHLAND WHITE TERRIER"),
	WHIPPET("WHIPPET", "WHIPPET"),
	YORKSHIRE("YORKSHIRE", "YORKSHIRE TERRIER"),
	OUTROS("OUTROS", "OUTROS");
	
	private String sigla;
	private String descricao;
	
	Raca(String sigla, String descricao){
		this.sigla = sigla;
		this.descricao = descricao;
	}

	public String getSigla() {
		return sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
}
